title: #BaerPlag
tagline: Ist was dran? Nö.
description: Ist was dran? Nö.
url: https://baerplag.de
lang: de_DE
defaults:
  - scope:
      path: ""
    values:
      image: /assets/img/obsolete_stadt_og_image.png

# Build settings
theme: jekyll-theme-tactile
plugins:
  - jekyll-seo-tag